name: Dispatch Docker Image manually

on:
  workflow_dispatch:

env:
  ECR_REGISTRY: 026343158313.dkr.ecr.ap-northeast-2.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ECR
        id: login-ecr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/juni:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: DEPLOY_TYPE=live